# this file will run a testrunner against the specified image
# run it with:
# docker-compose up --exit-code-from sdk_test_server

version: '3'
services:
  sdk_test_server:
      build:
        context: .
        dockerfile: Dockerfile
      image: sdk:py3
      environment:
        - MBED_CLOUD_SDK_API_KEY=abc123
        - CI=yes
      volumes:
        - ./results:/build/results
        - ./test_fixtures:/test_fixtures
      command: [sh, -c, 'source .venv/bin/activate && pytest -x tests/integration']
  testrunner:
      build:
        # this assumes you have a checkout of the testrunner alongside the sdk
        context: '../mbed-cloud-sdk-testrunner'
        args:
          - GIT_ACCESS_TOKEN
      image: '104059736540.dkr.ecr.us-west-2.amazonaws.com/mbed/sdk-testrunner:master'
      environment:
        - 'TEST_SERVER_URL=http://sdk_test_server:5000'
        - TEST_FIXTURES_DIR=/test_fixtures
        - TEST_RUNNER_SHUTDOWN_SERVER=yes
        - TEST_RUNNER_DEFAULT_API_KEY
        - TEST_RUNNER_DEFAULT_API_HOST
      depends_on:
        - sdk_test_server
      volumes:
        - ./results:/runner/results
        - ./test_fixtures:/runner/test_fixtures
